# Generated by Django 5.0.2 on 2024-02-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available', models.IntegerField()),
                ('Player', models.CharField(max_length=100)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Type', models.IntegerField()),
                ('Score', models.IntegerField()),
            ],
            options={
                'ordering': ['Date'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelName', models.CharField(max_length=100)),
                ('LevelId', models.IntegerField()),
                ('BallRec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ball', to='wogrecords.record')),
                ('MoveRec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Move', to='wogrecords.record')),
                ('OCDTimeRec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OCDTime', to='wogrecords.record')),
                ('TimeRec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Time', to='wogrecords.record')),
            ],
        ),
    ]
