# Generated by Django 5.0.2 on 2024-02-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Player',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
