# Generated by Django 5.0.2 on 2024-02-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0002_record_level_alter_record_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Level',
        ),
        migrations.AddField(
            model_name='record',
            name='Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
