# Generated by Django 5.0.2 on 2024-02-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0003_remove_record_level_record_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['LevelId']},
        ),
        migrations.RemoveField(
            model_name='level',
            name='BallRec',
        ),
        migrations.RemoveField(
            model_name='level',
            name='MoveRec',
        ),
        migrations.RemoveField(
            model_name='level',
            name='OCDTimeRec',
        ),
        migrations.RemoveField(
            model_name='level',
            name='TimeRec',
        ),
        migrations.AddField(
            model_name='level',
            name='BallRec',
            field=models.ManyToManyField(blank=True, related_name='Ball', to='wogrecords.record'),
        ),
        migrations.AddField(
            model_name='level',
            name='MoveRec',
            field=models.ManyToManyField(blank=True, related_name='Move', to='wogrecords.record'),
        ),
        migrations.AddField(
            model_name='level',
            name='OCDTimeRec',
            field=models.ManyToManyField(blank=True, related_name='OCDTime', to='wogrecords.record'),
        ),
        migrations.AddField(
            model_name='level',
            name='TimeRec',
            field=models.ManyToManyField(blank=True, related_name='Time', to='wogrecords.record'),
        ),
    ]
