# Generated by Django 5.0.2 on 2024-02-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0006_alter_record_options_record_link_alter_record_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='LevelName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('T', 'Time'), ('M', 'Moves'), ('B', 'Balls')], default='B', max_length=2),
        ),
    ]
