# Generated by Django 5.0.2 on 2024-02-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0007_record_description_record_levelname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('T', 'Time'), ('M', 'Moves'), ('O', 'OCDTime')], default='B', max_length=2),
        ),
    ]
