# Generated by Django 5.0.2 on 2024-02-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0008_alter_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('M', 'Moves'), ('T', 'Time'), ('B', 'Balls')], default='B', max_length=2),
        ),
    ]
