# Generated by Django 5.0.2 on 2024-03-03 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0009_alter_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name="Write the player's Name")),
                ('Description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'ordering': ['-Name'],
            },
        ),
        migrations.RemoveField(
            model_name='record',
            name='LevelName',
        ),
        migrations.AlterField(
            model_name='level',
            name='BallRec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ball', to='wogrecords.record'),
        ),
        migrations.AlterField(
            model_name='level',
            name='MoveRec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Move', to='wogrecords.record'),
        ),
        migrations.AlterField(
            model_name='level',
            name='OCDTimeRec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OCDTime', to='wogrecords.record'),
        ),
        migrations.AlterField(
            model_name='level',
            name='TimeRec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Time', to='wogrecords.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Available',
            field=models.IntegerField(verbose_name='Write 0 if record is N/A, otherwise 1'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Name',
            field=models.CharField(max_length=100, verbose_name="Identify the Record with 'Level-Score', *MUST NOT* contain spaces, use dash(-) instead"),
        ),
        migrations.AlterField(
            model_name='record',
            name='Score',
            field=models.IntegerField(verbose_name='Score, in *MILLISECONDS* for time records'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('T', 'Time'), ('M', 'Moves'), ('O', 'OCDTime'), ('B', 'Balls')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='record',
            name='Player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player', to='wogrecords.player'),
        ),
    ]
