# Generated by Django 5.0.2 on 2024-03-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0010_player_remove_record_levelname_alter_level_ballrec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['Name']},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Player',
            new_name='RecordPlayer',
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('T', 'Time'), ('O', 'OCDTime'), ('B', 'Balls'), ('M', 'Moves')], default='B', max_length=2),
        ),
    ]
