# Generated by Django 5.0.2 on 2024-03-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0011_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('B', 'Balls'), ('T', 'Time'), ('M', 'Moves')], default='B', max_length=2),
        ),
    ]
