# Generated by Django 5.0.2 on 2024-03-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0012_alter_record_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='RecordPlayer',
        ),
        migrations.AddField(
            model_name='record',
            name='Player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player', to='wogrecords.player'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('T', 'Time'), ('B', 'Balls'), ('M', 'Moves')], default='B', max_length=2),
        ),
    ]
