# Generated by Django 5.0.2 on 2024-03-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0013_remove_record_recordplayer_record_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Player',
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('T', 'Time'), ('M', 'Moves'), ('O', 'OCDTime')], default='B', max_length=2),
        ),
    ]
