# Generated by Django 5.0.2 on 2024-03-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0014_remove_record_player_alter_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('M', 'Moves'), ('O', 'OCDTime'), ('T', 'Time')], default='B', max_length=2),
        ),
    ]
