# Generated by Django 5.0.2 on 2024-03-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0015_alter_record_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('M', 'Moves'), ('B', 'Balls'), ('T', 'Time'), ('O', 'OCDTime')], default='B', max_length=2),
        ),
    ]
