# Generated by Django 5.0.2 on 2024-03-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0016_delete_player_alter_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name="Write the player's Name")),
                ('Description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('B', 'Balls'), ('M', 'Moves'), ('T', 'Time')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='record',
            name='Player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player', to='wogrecords.player'),
        ),
    ]
