# Generated by Django 5.0.2 on 2024-03-03 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0017_player_alter_record_type_record_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='BallRec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls', to='wogrecords.record'),
        ),
        migrations.AlterField(
            model_name='level',
            name='MoveRec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='wogrecords.record'),
        ),
        migrations.AlterField(
            model_name='level',
            name='OCDTimeRec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocdtimes', to='wogrecords.record'),
        ),
        migrations.AlterField(
            model_name='level',
            name='TimeRec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='wogrecords.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('M', 'Moves'), ('O', 'OCDTime'), ('T', 'Time')], default='B', max_length=2),
        ),
    ]
