# Generated by Django 5.0.2 on 2024-03-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0018_alter_level_ballrec_alter_level_moverec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='wogrecords.player'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('B', 'Balls'), ('T', 'Time'), ('M', 'Moves')], default='B', max_length=2),
        ),
        migrations.CreateModel(
            name='Record2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available', models.IntegerField(verbose_name='Write 0 if record is N/A, otherwise 1')),
                ('Name', models.CharField(max_length=100, verbose_name="Identify the Record with 'Level-Score', *MUST NOT* contain spaces, use dash(-) instead")),
                ('Date', models.DateField(blank=True, null=True, verbose_name='Date Achieved')),
                ('Type', models.CharField(choices=[('O', 'OCDTime'), ('B', 'Balls'), ('T', 'Time'), ('M', 'Moves')], default='B', max_length=2)),
                ('Score', models.IntegerField(verbose_name='Score, in *MILLISECONDS* for time records')),
                ('Link', models.URLField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=10000, null=True)),
                ('Player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='wogrecords.player')),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelName', models.CharField(max_length=100)),
                ('LevelId', models.IntegerField()),
                ('BallRec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls', to='wogrecords.record2')),
                ('MoveRec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='wogrecords.record2')),
                ('OCDTimeRec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocdtimes', to='wogrecords.record2')),
                ('TimeRec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='wogrecords.record2')),
            ],
            options={
                'ordering': ['LevelId'],
            },
        ),
    ]
