# Generated by Django 5.0.2 on 2024-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0019_alter_record_player_alter_record_type_record2_level2'),
    ]

    operations = [
        migrations.AddField(
            model_name='record2',
            name='LevelName',
            field=models.CharField(default=0, max_length=100, verbose_name="Name of record's level. Copy the EXACT name of LEVEL, INCLUDING spaces."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('M', 'Moves'), ('B', 'Balls'), ('T', 'Time')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='record2',
            name='Name',
            field=models.CharField(max_length=100, verbose_name="Identify the Record with 'LevelName-Score', *MUST NOT* contain spaces, use dash(-) instead"),
        ),
        migrations.AlterField(
            model_name='record2',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('M', 'Moves'), ('B', 'Balls'), ('T', 'Time')], default='B', max_length=2),
        ),
    ]
