# Generated by Django 5.0.2 on 2024-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0020_record2_levelname_alter_record_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='LevelName',
            field=models.CharField(default=0, max_length=100, verbose_name="Name of record's level. Copy the EXACT name of LEVEL, INCLUDING spaces."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('M', 'Moves'), ('O', 'OCDTime'), ('B', 'Balls'), ('T', 'Time')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='record2',
            name='Type',
            field=models.CharField(choices=[('M', 'Moves'), ('O', 'OCDTime'), ('B', 'Balls'), ('T', 'Time')], default='B', max_length=2),
        ),
    ]
