# Generated by Django 5.0.2 on 2024-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0021_record_levelname_alter_record_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record2',
            name='Player',
        ),
        migrations.AlterField(
            model_name='record',
            name='LevelName',
            field=models.CharField(max_length=100, verbose_name='Copy the EXACT name of LEVEL written on main site, INCLUDING spaces.'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Name',
            field=models.CharField(max_length=100, verbose_name="Use 'LevelName-Record', *MUST NOT* contain spaces, use dash (-) instead"),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('T', 'Time'), ('B', 'Balls'), ('O', 'OCDTime'), ('M', 'Moves')], default='B', max_length=2),
        ),
        migrations.DeleteModel(
            name='Level2',
        ),
        migrations.DeleteModel(
            name='Record2',
        ),
    ]
