# Generated by Django 5.0.2 on 2024-03-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0022_remove_record2_player_alter_record_levelname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='DownloadLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('M', 'Moves'), ('O', 'OCDTime'), ('B', 'Balls'), ('T', 'Time')], default='B', max_length=2),
        ),
    ]
