# Generated by Django 5.0.2 on 2024-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0023_record_downloadlink_alter_record_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['Date']},
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('B', 'Balls'), ('M', 'Moves'), ('T', 'Time')], default='B', max_length=2),
        ),
    ]
