# Generated by Django 5.0.2 on 2024-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0027_alter_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('O', 'OCDTime'), ('M', 'Moves'), ('B', 'Balls'), ('T', 'Time')], default='B', max_length=2),
        ),
    ]
