# Generated by Django 5.0.2 on 2024-06-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0028_alter_record_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-Date']},
        ),
    ]
