# Generated by Django 5.0.2 on 2024-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0029_alter_record_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='Version',
            field=models.CharField(default='1.3', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='Description_notes',
            field=models.TextField(blank=True, max_length=16384, null=True, verbose_name='Notes from Website Managers'),
        ),
        migrations.AddField(
            model_name='record',
            name='ImageLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Description',
            field=models.TextField(blank=True, max_length=16384, null=True, verbose_name="Player's comments"),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('M', 'Moves'), ('T', 'Time'), ('O', 'OCDTime')], default='B', max_length=2),
        ),
    ]
