# Generated by Django 5.0.2 on 2024-06-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0030_level_version_record_description_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('M', 'Moves'), ('T', 'Time'), ('O', 'OCDTime'), ('B', 'Balls')], default='B', max_length=2),
        ),
    ]
