# Generated by Django 5.0.2 on 2024-06-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0032_alter_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Balls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Balls'),
        ),
        migrations.AddField(
            model_name='player',
            name='Moves',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Moves'),
        ),
        migrations.AddField(
            model_name='player',
            name='Time',
            field=models.TimeField(blank=True, null=True, verbose_name='Total Time'),
        ),
        migrations.AlterField(
            model_name='level',
            name='LevelName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='level',
            name='Version',
            field=models.CharField(default='1.3', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='Description',
            field=models.TextField(blank=True, max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(max_length=128, verbose_name="Write the player's Name"),
        ),
        migrations.AlterField(
            model_name='record',
            name='DownloadLink',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ImageLink',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='LevelName',
            field=models.CharField(max_length=128, verbose_name='Copy the EXACT name of LEVEL written on main site, INCLUDING spaces.'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Link',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Name',
            field=models.CharField(max_length=128, verbose_name="Use 'LevelName-Record', *MUST NOT* contain spaces, use dash (-) instead"),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('O', 'OCDTime'), ('M', 'Moves'), ('T', 'Time')], default='B', max_length=2),
        ),
    ]
