# Generated by Django 5.0.2 on 2024-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0033_player_balls_player_moves_player_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Balls',
            field=models.IntegerField(default=0, verbose_name='Total Balls'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Moves',
            field=models.IntegerField(default=9999, verbose_name='Total Moves'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Time',
            field=models.IntegerField(default=99999000, verbose_name='Total Time (milliseconds)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('T', 'Time'), ('O', 'OCDTime'), ('M', 'Moves')], default='B', max_length=2),
        ),
    ]
