# Generated by Django 5.0.2 on 2024-07-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0034_alter_player_balls_alter_player_moves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('M', 'Moves'), ('O', 'OCDTime'), ('B', 'Balls'), ('T', 'Time')], default='B', max_length=2),
        ),
        migrations.CreateModel(
            name='Record2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available', models.IntegerField(verbose_name='Write 0 if record is N/A, otherwise 1')),
                ('Name', models.CharField(max_length=128, verbose_name="Use 'LevelName-Record', *MUST NOT* contain spaces, use dash (-) instead")),
                ('LevelName', models.CharField(max_length=128, verbose_name='Copy the EXACT name of LEVEL written on main site, INCLUDING spaces.')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='Date Achieved')),
                ('Type', models.CharField(choices=[('M', 'Moves'), ('O', 'OCDTime'), ('B', 'Balls'), ('T', 'Time')], default='B', max_length=2)),
                ('Score', models.IntegerField(verbose_name='Score, in *MILLISECONDS* for time records')),
                ('Link', models.URLField(blank=True, max_length=256, null=True)),
                ('DownloadLink', models.URLField(blank=True, max_length=256, null=True)),
                ('ImageLink', models.URLField(blank=True, max_length=256, null=True)),
                ('Description', models.TextField(blank=True, max_length=16384, null=True, verbose_name="Player's comments")),
                ('Description_notes', models.TextField(blank=True, max_length=16384, null=True, verbose_name='Notes from Website Managers')),
                ('Player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='wogrecords.player')),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
    ]
