# Generated by Django 5.0.2 on 2024-07-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0037_alter_record_type_alter_record2_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('O', 'OCDTime'), ('T', 'Time'), ('M', 'Moves')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='record2',
            name='Type',
            field=models.CharField(choices=[('B', 'Balls'), ('O', 'OCDTime'), ('T', 'Time'), ('M', 'Moves')], default='B', max_length=2),
        ),
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelName', models.CharField(max_length=128)),
                ('LevelId', models.IntegerField()),
                ('Version', models.CharField(default='2.0', max_length=10)),
                ('BallRec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls', to='wogrecords.record2')),
                ('MoveRec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='wogrecords.record2')),
                ('OCDTimeRec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocdtimes', to='wogrecords.record2')),
                ('TimeRec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='wogrecords.record2')),
            ],
            options={
                'ordering': ['LevelId'],
            },
        ),
    ]
