# Generated by Django 5.0.2 on 2024-08-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0038_alter_record_type_alter_record2_type_level2'),
    ]

    operations = [
        migrations.AddField(
            model_name='record2',
            name='BelongLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record2', to='wogrecords.level2'),
        ),
        migrations.AddField(
            model_name='record2',
            name='ExactTime',
            field=models.TimeField(blank=True, null=True, verbose_name='exact time Achieved'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('T', 'Time'), ('M', 'Moves'), ('B', 'Balls'), ('O', 'OCDTime')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='record2',
            name='LevelName',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Leave Blank'),
        ),
        migrations.AlterField(
            model_name='record2',
            name='Name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Leave Blank'),
        ),
        migrations.AlterField(
            model_name='record2',
            name='Type',
            field=models.CharField(choices=[('T', 'Time'), ('M', 'Moves'), ('B', 'Balls'), ('O', 'OCDTime')], default='B', max_length=2),
        ),
    ]
