# Generated by Django 5.0.2 on 2024-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wogrecords', '0039_record2_belonglevel_record2_exacttime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record2',
            options={'ordering': ['-Date', '-ExactTime']},
        ),
        migrations.AlterField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('M', 'Moves'), ('B', 'Balls'), ('T', 'Time'), ('O', 'OCDTime')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='record2',
            name='Type',
            field=models.CharField(choices=[('M', 'Moves'), ('B', 'Balls'), ('T', 'Time'), ('O', 'OCDTime')], default='B', max_length=2),
        ),
    ]
